# If want to input None, use !!null

gpu0: 'cuda0'
gpu1: 'cuda1'
# sock_gpu: 5000
# sock_data0: 5003
# sock_data1: 5004

batch_size: 128 # def: 128

# Directories
train_folder: /scratch/ilsvrc12/train_hkl_b256_b_128/
val_folder: /scratch/ilsvrc12/val_hkl_b256_b_128/
